### ISSUE TITLE
Encode Error

### ISSUE THREAD

**Issue by StudyingFather** [memset0/luogu-todolist#1]
在按照要求添加题目后，出现了编码错误的问题：

![](https://cdn.luogu.org/upload/pic/49667.png)

**Comment by StudyingFather** [comment]
把GBK编码换成UTF-8后这一问题仍然没有解决。

**Comment by StudyingFather** [comment]
似乎只有P1000的编码是错乱的，其他题目都是正常的...

不过还是希望能修复一下这个不大不小的问题。

**Comment by memset0** [comment]
这个问题我也不知道怎么修。。。

您把 host.py 里的那个 `gbk` 改成 `utf8` 试试？

**Comment by StudyingFather** [comment]
试着改过了，本来只有P1000是错乱的，改到UTF-8之后所有带中文的全部乱码了...

**Comment by Tiger3018** [comment]
首先先看一下浏览器是用什么字符编码显示？（如果是Firefox就应该可以自行修改）

或者html加上`<meta charset="utf-8" />` `<meta charset="gb2312" />` `<meta http-equiv="Content-Type" content="text/html; charset=gb2312" /> `

**Comment by memset0** [comment]
哦，我知道了，您把 `cache/title.yml` 删除试试？

**Comment by StudyingFather** [comment]
问题修复了，非常感谢。
