### ISSUE TITLE
建议添加自定义端口功能

### ISSUE THREAD

**Issue by quank123wip** [memset0/luogu-todolist#9]
2333这个端口很容易被shadowsocks,v2ray等占用,对于某些小白不是很友好,建议添加该功能避免端口冲突

**Comment by memset0** [comment]
可以自行修改 py 源码

短期内不打算增加这个功能

**Comment by quank123wip** [comment]
@memset0 Orz那我添加一个然后发pull request啊

**Comment by memset0** [comment]
不需要，等其他功能完善后此类东西会统一做掉...
